name: CI Pipeline

on:
          pull_request:
                      branches:
                                    - main  # Trigger the workflow only on pull requests to the main branch

                      jobs:
                                test:
                                            runs-on: ubuntu-latest  # Set the runner environment, e.g., Ubuntu

                                                steps:
                                                            - name: Checkout repository
                                                                    uses: actions/checkout@v2  # Check out the code to the runner

                                                                        - name: Set up Python
                                                                                uses: actions/setup-python@v4
                                                                                      with:
                                                                                                      python-version: 3.8  # Define the Python version

                                                                                                          - name: Install dependencies
                                                                                                                  run: |
                                                                                                                                  python -m venv venv
                                                                                                                                          source venv/bin/activate
                                                                                                                                                  pip install -r requirements.txt  # Install dependencies from requirements.txt

                                                                                                                                                      - name: Run tests with pytest
                                                                                                                                                              run: |
                                                                                                                                                                              source venv/bin/activate
                                                                                                                                                                                      pytest  # Run the tests with pytest


