name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy_to_server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH and deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Debugging: Print environment and check if docker and nginx are installed
            echo "Checking Docker and Nginx"
            docker --version
            nginx -v

            # Pull latest code from GitHub repository
            cd /var/www/fastapi-book-project
            git pull origin main

            # Restart Docker containers and Nginx
            sudo docker-compose down
            sudo docker-compose up -d --build
            sudo systemctl restart nginx
