name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy_to_server:  depoy_to_server 
    runs-on: ubuntu-latest
    needs: test  # Ensure deploy only happens after successful tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Load private SSH key from secrets

      - name: SSH into server and deploy
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            echo "Pulling latest code on the server"
            cd /var/www/fastapi-book-project || exit
            git pull origin main || exit
            echo "Stopping and rebuilding Docker containers"
            sudo docker compose down || exit
            sudo docker compose up -d --build || exit
            echo "Restarting Nginx"
            sudo systemctl restart nginx || exit
            echo "Deployment successful"
          EOF
