name: Deploy FastAPI to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Expect (for password-based SSH)
        run: sudo apt-get update && sudo apt-get install -y expect

      - name: Deploy to Server
        run: |
          mkdir -p ~/.ssh
          echo -e "Host ${{ secrets.SERVER_HOST }}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
          chmod 600 ~/.ssh/config
          expect <<EOF
          spawn ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}
          expect {
            -re "Are you sure you want to continue connecting.*" {
              send "yes\r"
              exp_continue
            }
            "password:" {
              send "${{ secrets.SERVER_PASSWORD }}\r"
            }
          }
          expect "$ "
          send "cd /var/www/fastapi-book-project && git pull origin main\r"
          expect "$ "
          send "sudo docker stop \$(sudo docker ps -q) || true\r"
          expect "$ "
          send "sudo docker rm \$(sudo docker ps -a -q) || true\r"
          expect "$ "
          send "sudo docker-compose up -d\r"
          expect "$ "
          send "exit\r"
          EOF
